[package]
name = "delaunay-stabilization"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.3"
nannou = "0.18.1"
petgraph = "0.6.0"
rustc-hash = "1.1.0"
spade = "2.0.0"


[profile.dev]
opt-level = 1
overflow-checks = false

[profile.dev.package."*"]
opt-level = 2
